version: '3'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # Client connections
      - "6222:6222"  # Clustering
      - "8222:8222"  # HTTP monitoring
    command: [
      "--jetstream",
      "--store_dir=/data",
      "--http_port=8222"
    ]
    volumes:
      - ./nats-data:/data
    restart: unless-stopped