version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"    # Client connections
      - "6222:6222"    # Route connections (for clustering)
      - "8222:8222"    # HTTP monitoring
      - "7777:7777"    # Websocket connections
    command:
      - "-js"
      - "-m=8222"
      - "--store-dir=/data"
      - "--debug=true"  # Enable debug logging
    volumes:
      - nats-data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  nats-data: